name: Release

# on:
#   push:
#     branches:
#       - main
#     paths:
#       - "src/**"
#       - "**/CMakeLists.txt"
#       - "**/CMakePresets.json"
#       - "vcpkg.json"
#   workflow_call:
#   workflow_dispatch:

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  release:
    needs: build

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          path: ./build/release/
          pattern: build-output-*
          merge-multiple: true

      - name: Create release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: v${{ needs.build.outputs.project_version }}
          name: v${{ needs.build.outputs.project_version }}
          working_directory: build/release/
          files: "ZomboidAssetConverter-*.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
